export const FETCH_POST_DETAILS_PENDING = 'FETCH_POST_DETAILS_PENDING';
export const FETCH_POST_DETAILS_SUCCESS = 'FETCH_POST_DETAILS_SUCCESS';
export const FETCH_POST_DETAILS_ERROR = 'FETCH_POST_DETAILS_ERROR';
